var path = require('path');
var webpack = require('webpack');
var TimestampWebpackPlugin = require('timestamp-webpack-plugin');

var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  context:   path.resolve('js'),
  entry:     ['./utils','./app'],
  output:    {
    path:       path.resolve('build/js/'),
    publicPath: 'public/assets/js/',
    filename:   'bundle.js'
  },
  plugins:   [
      new ExtractTextPlugin("styles.css"),
      new webpack.ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery',
        'window.jQuery': 'jquery'
      }),
      new TimestampWebpackPlugin({
        path: __dirname,
        filename: 'timestamp.json'
      }),
      new webpack.BannerPlugin("****\nGenerated by Webpack!\n****")
  ],
  devServer: {
    contentBase: 'public'
  },
  module:    {
    preLoaders: [
      {
        test:    /\.js$/,
        exclude: /node_modules/,
        loader:  'eslint-loader'
      }
    ],
    loaders:    [
      {
        test:   /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: "url-loader?limit=10000&minetype=application/font-woff"
      },
      {
        test:   /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: "file-loader"
      },
      {
        test: /\.(png|jpg|ttf|eot|svg)$/,
        exclude: /node_modules/,
        loader: 'url-loader?limit=10000'
      },
      {
        test:    /\.s?css$/,
        exclude: /node_modules/,
        loader:  ExtractTextPlugin.extract("style-loader", "css-loader!sass-loader", { publicPath: './'})
      },
      {
        test:    /\.es6$/,
        exclude: /node_modules/,
        loader:  'babel-loader'
      }
    ]
  },
  resolve:   {
    extensions: ['', '.js', '.es6']
  }
};